install.packages("arules")
install.packages("shiny")
install.packages("shinythemes")
install.packages("data.table")
install.packages("ggplot2")
install.packages("ggthemes")
install.packages("viridis")
install.packages("extrafont")
install.packages("DT")
install.packages("plotly")
install.packages("Cairo")
install.packages("igraph")
install.packages("visNetwork")
install.packages("dplyr")
install.packages("magrittr")
install.packages("arulesViz")

